--------------------------------------------------------
--  File created - Wednesday-March-21-2018   
--------------------------------------------------------
DROP SEQUENCE "IBDS"."SEQ_CANAL";
DROP SEQUENCE "IBDS"."SEQ_LOGS";
DROP SEQUENCE "IBDS"."SEQ_PERIODO";
DROP TABLE "IBDS"."CANAL";
DROP TABLE "IBDS"."CATEGORIA";
DROP TABLE "IBDS"."LOGS";
DROP TABLE "IBDS"."PERIODO";
DROP TABLE "IBDS"."TRANSACCION";
DROP TABLE "IBDS"."USUARIO";
--------------------------------------------------------
--  DDL for Sequence SEQ_CANAL
--------------------------------------------------------

   CREATE SEQUENCE  "IBDS"."SEQ_CANAL"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOGS
--------------------------------------------------------

   CREATE SEQUENCE  "IBDS"."SEQ_LOGS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 549821 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PERIODO
--------------------------------------------------------

   CREATE SEQUENCE  "IBDS"."SEQ_PERIODO"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CANAL
--------------------------------------------------------

  CREATE TABLE "IBDS"."CANAL" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "IBDS"."CATEGORIA" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"ORDEN" NUMBER, 
	"FILL" VARCHAR2(10 BYTE), 
	"COLOR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Table LOGS
--------------------------------------------------------

  CREATE TABLE "IBDS"."LOGS" 
   (	"ID" NUMBER, 
	"USUARIO" NUMBER, 
	"CANAL" NUMBER, 
	"TRANSACCION" NUMBER, 
	"ERROR" VARCHAR2(20 BYTE), 
	"FECHA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Table PERIODO
--------------------------------------------------------

  CREATE TABLE "IBDS"."PERIODO" 
   (	"ID" NUMBER, 
	"VALOR" NUMBER, 
	"RANGO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Table TRANSACCION
--------------------------------------------------------

  CREATE TABLE "IBDS"."TRANSACCION" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"CATEGORIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "IBDS"."USUARIO" 
   (	"ID" NUMBER, 
	"FECHA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Index TRANSACCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBDS"."TRANSACCION_PK" ON "IBDS"."TRANSACCION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBDS"."USUARIO_PK" ON "IBDS"."USUARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Index CANAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBDS"."CANAL_PK" ON "IBDS"."CANAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Index LOGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBDS"."LOGS_PK" ON "IBDS"."LOGS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Index PERIODO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBDS"."PERIODO_PK" ON "IBDS"."PERIODO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Index PERIODO_IDX_RANGO
--------------------------------------------------------

  CREATE INDEX "IBDS"."PERIODO_IDX_RANGO" ON "IBDS"."PERIODO" ("RANGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Index CATEGORIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBDS"."CATEGORIA_PK" ON "IBDS"."CATEGORIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS" ;
--------------------------------------------------------
--  DDL for Trigger TGR_PERIODO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IBDS"."TGR_PERIODO" 
   before insert on "IBDS"."PERIODO" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select SEQ_PERIODO.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "IBDS"."TGR_PERIODO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CANAL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IBDS"."TRG_CANAL" 
   before insert on "IBDS"."CANAL" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select SEQ_CANAL.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;



/
ALTER TRIGGER "IBDS"."TRG_CANAL" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_LOGS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IBDS"."TRG_LOGS" 
   before insert on "IBDS"."LOGS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select SEQ_LOGS.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;


/
ALTER TRIGGER "IBDS"."TRG_LOGS" ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACCION
--------------------------------------------------------

  ALTER TABLE "IBDS"."TRANSACCION" ADD CONSTRAINT "TRANSACCION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS"  ENABLE;
  ALTER TABLE "IBDS"."TRANSACCION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "IBDS"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS"  ENABLE;
  ALTER TABLE "IBDS"."USUARIO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "IBDS"."CATEGORIA" ADD CONSTRAINT "CATEGORIA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS"  ENABLE;
  ALTER TABLE "IBDS"."CATEGORIA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOGS
--------------------------------------------------------

  ALTER TABLE "IBDS"."LOGS" ADD CONSTRAINT "LOGS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS"  ENABLE;
  ALTER TABLE "IBDS"."LOGS" MODIFY ("TRANSACCION" NOT NULL ENABLE);
  ALTER TABLE "IBDS"."LOGS" MODIFY ("CANAL" NOT NULL ENABLE);
  ALTER TABLE "IBDS"."LOGS" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "IBDS"."LOGS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERIODO
--------------------------------------------------------

  ALTER TABLE "IBDS"."PERIODO" ADD CONSTRAINT "PERIODO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS"  ENABLE;
  ALTER TABLE "IBDS"."PERIODO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANAL
--------------------------------------------------------

  ALTER TABLE "IBDS"."CANAL" ADD CONSTRAINT "CANAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IBDS"  ENABLE;
  ALTER TABLE "IBDS"."CANAL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "IBDS"."CANAL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LOGS
--------------------------------------------------------

  ALTER TABLE "IBDS"."LOGS" ADD CONSTRAINT "LOGS_FK_CANAL" FOREIGN KEY ("CANAL")
	  REFERENCES "IBDS"."CANAL" ("ID") ENABLE;
  ALTER TABLE "IBDS"."LOGS" ADD CONSTRAINT "LOGS_FK_TRANSACCION" FOREIGN KEY ("TRANSACCION")
	  REFERENCES "IBDS"."TRANSACCION" ("ID") ENABLE;
  ALTER TABLE "IBDS"."LOGS" ADD CONSTRAINT "LOGS_FK_USUARIO" FOREIGN KEY ("USUARIO")
	  REFERENCES "IBDS"."USUARIO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACCION
--------------------------------------------------------

  ALTER TABLE "IBDS"."TRANSACCION" ADD CONSTRAINT "TRANSACCION_FK_CATEGORIA" FOREIGN KEY ("CATEGORIA")
	  REFERENCES "IBDS"."CATEGORIA" ("ID") ENABLE;
