--------------------------------------------------------
--  File created - Wednesday-March-21-2018   
--------------------------------------------------------
REM INSERTING into IBDS.TRANSACCION
SET DEFINE OFF;
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (283,'Agendar Transferencia PDS',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (202,'Afiliar Beneficiario',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (190,'Posición Consolidada',5);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (12,'Detalle de Mov. de Cta.',6);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1098,'Inicio de Sesión',2);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1099,'Cierre de Sesión',1);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1102,'Detalle de TDC',6);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (3,'Terceros Otros Bancos',3);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1100,'Detalle de Cuenta',6);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (185,'Terceros Otros Bancos',3);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (481,'Desbloqueo de usuario',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (204,'Crear Clave Operaciones Especiales',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (365,'Actualización de Datos',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1101,'Detalle de Mov. de Cta.',6);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1861,'Afiliación  ',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (222,'Cambio de Clave',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (11,'Detalle de Cuentas',6);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (99,'Cierre de Sesión',1);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1,'Terceros DELSUR',3);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1921,' Pagar',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (98,'Inicio de Sesión',2);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (184,'Terceros DELSUR',3);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (261,'Registro de Usuario',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (322,'Histórico Transacciones',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (201,'Directorio de Beneficiarios',6);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (182,'Propias DELSUR',4);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (6,'Propias DELSUR',4);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1823,'Recarga',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (321,'Límites',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1881,'Editar Afiliación',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (183,'Propias Otros Bancos',4);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (381,'Solicitud de Chequeras',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (7,'Propias Otros Bancos',4);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1961,'Reinicio de Usuario',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (221,'Olvidó su Clave',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1822,'Desafiliación',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (203,'Reiniciar/Cambio Clave Operaciones Especiales',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (402,'Consulta de Reclamos',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (13,'Detalle de TDC',6);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (187,'Propias Otros Bancos',4);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1821,'Afiliación',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (382,'Referencia Bancaria',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (462,'Consulta Pagos Programados',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (188,'Terceros DELSUR',3);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (186,'Propias DELSUR',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (181,'Consulta de Estatus de Cheques',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (189,'Terceros Otros Bancos',3);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1103,'Detalle de Préstamo',6);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (205,'Consulta Solicitud de Chequera',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (241,'Cambio de Preguntas de Seguridad',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (2,'Propias DELSUR',4);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (8,'Propias Otros Bancos',4);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (401,'Suspender Chequeras',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (341,'Pago de Préstamos',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (5,'Terceros DELSUR',3);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1901,'Desafiliación',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1843,'Recarga',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (998,'Desconexión por múltiple sesión',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (4,'Terceros Otros Bancos',3);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (1998,'Desconexión por múltiple sesión',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (286,'Agendar Transferencia TOB',7);
Insert into IBDS.TRANSACCION (ID,NOMBRE,CATEGORIA) values (301,'Pagos agendados Propios en DELSUR',7);
