-- Generated by Oracle SQL Developer REST Data Services 17.4.1.054.0712
-- Exported REST Definitions from ORDS Schema Version 17.4.1.353.06.48
-- Schema: IBDS   Date: Wed Mar 21 13:41:10 VET 2018
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'IBDS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'ibds',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'categoria',
      p_base_path      => '/categoria/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'categoria',
      p_pattern        => '/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'categoria',
      p_pattern        => '/',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select 
    * 
from 
    categoria c 
where
    c.id > 0
order by c.ORDEN'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'logs',
      p_base_path      => '/logs/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'logs',
      p_pattern        => '/:fecha',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'logs',
      p_pattern        => '/:fecha',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_cursor SYS_REFCURSOR;
BEGIN
open l_cursor for 
    SELECT 
        p.valor as hora,
        cursor(
            select 
                t.categoria, count(*) as total
            from
                LOGS l
                inner join TRANSACCION t on l.TRANSACCION = t.ID
            where to_char(l.fecha, ''HH24'') = p.VALOR and to_char(l.fecha, ''YYYYMMDD'') = :fecha
            group by t.categoria

        ) as categorias
    FROM 
        periodo p
    WHERE
        p.rango = ''hora'';

APEX_JSON.open_object;        
APEX_JSON.write(''logs'', l_cursor);
APEX_JSON.close_object;

END;'
      );


  COMMIT; 
END;