-- Generated by Oracle SQL Developer REST Data Services 17.4.1.054.0712
-- Exported REST Definitions from ORDS Schema Version 17.4.1.353.06.48
-- Schema: IBDS   Date: Tue Mar 20 16:15:36 VET 2018
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'IBDS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'ibds',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'canales',
      p_base_path      => '/canal/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'canales',
      p_pattern        => '/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'canales',
      p_pattern        => '/',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
    *
FROM
    canal'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'canales',
      p_pattern        => '/:canal',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'canales',
      p_pattern        => '/:canal',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from canal where nombre = :canal'
      );


  COMMIT; 
END;